"""Where is pi, actually? Go through the ledger's PROVED column and check."""
import sys
try: sys.stdout.reconfigure(encoding="utf-8")
except Exception: pass
from mpmath import mp, mpf, pi, sqrt, gamma, exp, nstr, jtheta
mp.dps = 25

print("=== every PROVED result, checked for pi ===")
print()
print("1. parity theorem  S(m) = 0 for odd m")
print("   a finite sum of +/-1 on a lattice ring.  S(1)=", 0, " S(5)=", 0)
print("   pi: ABSENT")
print()
print("2. character law   S(m) = (-1)^(m/2) r2(m) for even m")
print("   integers only.   pi: ABSENT")
print()
print("3. Theorem 4       T(m) = 2 sum S(m - k3^2)")
print("   integers only.   pi: ABSENT")
print()
print("4. T2 formula      T2(m) = m r2(m)/2 - 2 sum k1^2")
print("   integers only.   pi: ABSENT")
print()
print("5. R(2,2) = 2^s - 1  and  R(2,1) = (2^2s - 2^s)/2   -- for ALL s")
s = mpf(-1)/2
print("   at s=-1/2:  R(2,2) =", nstr(2**s - 1, 20))
print("               1/sqrt2 - 1 =", nstr(1/sqrt(2) - 1, 20))
print("   proof input: r2(2m) = r2(m).  Integers.")
print("   pi: ABSENT from the statement AND from the proof")
print()
print("6. A = 1 - 1/sqrt2 = -R(2,2) =", nstr(-(2**s - 1), 20), "   pi: ABSENT")
print()
print("7. d=3 has no doubling:  r3(1)=6, r3(2)=12.   pi: ABSENT")
print()
print("8. one mark kills the zero mode: |n+alpha|^2 != 0.  pi: ABSENT")
print()
print("9. 028's obstruction: e^(-2 pi sqrt2) cannot sit in a series in q=e^(-2 pi)")
print("   pi appears -- but in BOTH exponents. The content is that sqrt2 is irrational:")
print("   e^(-2 pi sqrt2) = q^sqrt2 requires sqrt2 in Z.  pi cancels out of the argument.")
print("   pi: PRESENT BUT INERT")
print()
print("10. Greg's halving half:  theta3 theta4 = theta4(q^2)^2, and 0 < theta4 < 1")
q = mpf('0.3')
print("    identity at q=0.3:", nstr(jtheta(3,0,q)*jtheta(4,0,q), 18), "=", nstr(jtheta(4,0,q*q)**2, 18))
print("    a q-series identity. No pi in it.")
print("    The sign flip uses Gamma(-1/2) =", nstr(gamma(s), 12), "-- only its SIGN is used.")
print("    pi: PRESENT BUT INERT (sign only)")
print()
print("11. monotonicity: theta3 > theta2 > 0, and Gamma(-1/2) < 0.  Same. INERT")
print()
print("="*66)
print("=== every OBSERVED result, same check ===")
print("="*66)
print("R  = 0.0416894146027237751...    pi: LOAD-BEARING")
print("eps, c2, d*, b', every slope     pi: LOAD-BEARING")
print("the functional equation prefactor pi^(-1-d/2) Gamma((d+1)/2)/Gamma(-1/2):")
for d in [2,3]:
    print(f"   d={d}: {nstr(pi**(-1-mpf(d)/2)*gamma((mpf(d)+1)/2)/gamma(s), 12)}")
print()
print("="*66)
print("=== and WHERE does pi enter the machinery? ===")
print("="*66)
print("   Gaussian integral      INT exp(-x^2) dx      =", nstr(sqrt(pi), 15))
print("   Gamma(1/2)                                   =", nstr(gamma(mpf(1)/2), 15), " (same thing)")
print("   heat kernel on the FLAT torus  (4 pi t)^(-d/2)")
print("   Poisson summation   sum exp(-t n^2) = sqrt(pi/t) sum exp(-pi^2 k^2/t)")
for tv in ['0.7','1.3']:
    t = mpf(tv)
    lhs = sum(exp(-t*mpf(n)**2) for n in range(-60,61))
    rhs = sqrt(pi/t)*sum(exp(-pi**2*k*k/t) for k in range(-60,61))
    print(f"      t={tv}: {nstr(lhs,15)} = {nstr(rhs,15)}")
print()
print("   EVERY pi in this programme enters through a GAUSSIAN.")
print("   Heat kernel, Mellin/Gamma, Ewald, Poisson -- all Gaussian machinery.")
